# Project information
site_name: DeepVariant-TrioTrain
site_author: Jenna Kalleberg
site_description: >-
  Extend DeepVariant automatically for species without GIAB-quality benchmark truth sets.

# Repository
repo_url: https://github.com/jkalleberg/DV-TrioTrain
repo_name: jkalleberg/DV-TrioTrain

# Page tree
nav:
  - Home: index.md
  - Getting Started:
      - Start Here!: getting-started/getting-started.md
      - Installation: getting-started/installation.md
      - Configuration Guide: getting-started/configuration.md
      - Human GIAB Tutorial: getting-started/walk-through.md
  - User Guide:
      - Overview: user-guide/usage_guide.md
      - Models: user-guide/existing_models.md
      - Getting help: user-guide/get-help.md
      - How to cite: user-guide/citation.md
  - About:
      - Learn more: about/about.md
      - License: about/license.md

plugins:
  - search
  - open-in-new-tab
  - git-revision-date-localized:
      type: date

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
    - content.code.copy

# Extensions
markdown_extensions:
  - admonition
  - def_list
  - del_ins
  - tables
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
